zaplings/urls.py
from django.conf.urls import patterns, url

from zaplings import views

urlpatterns = patterns('',
    url(r'^/?$', views.IndexView.as_view(), name='index'),
    url(r'^index-alt/?$', views.IndexAltView.as_view(), name='index-alt'),
    url(r'^creation-process/?$', views.CreationProcessView.as_view(), name='creation-process'),
    url(r'^creation-stages/?$', views.CreationStagesView.as_view(), name='creation-stages'),
    url(r'^our-mission/?$', views.MissionView.as_view(), name='our-mission'),
    url(r'^our-dream/?$', views.DreamView.as_view(), name='our-dream'),
    url(r'^rsvp-email/?$', views.RsvpEmail.as_view(), name='rsvp-email'),
    url(r'^blog/?$', views.BlogView.as_view(), name='blog'),
    # user login/signup 
    url(r'^signup/$', views.SignupView.as_view(), name='signup'),
    url(r'^signup_user/$', views.signup_user, name='signup_user'),
    url(r'^login_email_password/$', views.login_email_password, name='login_email_password'),
    url(r'^logout/$', views.user_logout, name='user_logout'),
    # profiles
    url(r'^profile/(?P<pk>\d+)/$', views.ProfileView.as_view(), name='profile'),
    url(r'^profile-text/$', views.ProfileTextView.as_view(), name='profile-text'),
    url(r'^profile-view/$', views.ViewProfileView.as_view(), name='profile-view'),
    # user tags
    url(r'^loves/$', views.LovesView.as_view(), name='loves'),
    url(r'^offers/$', views.OffersView.as_view(), name='offers'),
    url(r'^needs/$', views.NeedsView.as_view(), name='needs'),
    url(r'^creatorsnight/$', views.RsvpView.as_view(), name='creatorsnight'),
    url(r'^rsvp-confirm/$', views.RsvpConfirmView.as_view(), name='rsvp-confirm'),
    url(r'^(?P<userid>\d+)/generate_user_tags/$', views.generate_user_tags, name='generate_user_tags'),
    url(r'^generate_profile/$', views.generate_profile, name='generate_profile'),
    # form handlers
    url(r'^record_loves/$', views.record_loves, name='record_loves'),
    url(r'^record_offers/$', views.record_offers, name='record_offers'),
    url(r'^record_needs/$', views.record_needs, name='record_needs'),
    url(r'^record_new_email/$', views.record_new_email, name='record_new_email'),
    url(r'^record_text/$', views.record_text, name='record_text'),
    url(r'^record_feedback/$', views.record_feedback, name='record_feedback'),
    url(r'^process-rsvp/$', views.process_rsvp, name='process-rsvp'),
    # menu links
    url(r'^10-reasons/$', views.AboutView.as_view(), name='10-reasons'),
    url(r'^howitworks/$', views.HowItWorksView.as_view(), name='howitworks'),
    url(r'^getinvolved/$', views.GetInvolvedView.as_view(), name='getinvolved'),
    url(r'^faq/$', views.FaqView.as_view(), name='faq'),
    url(r'^discuss/$', views.DiscussView.as_view(), name='discuss'),
    # idea stuff
    url(r'^idea-feed/$', views.IdeaFeedView.as_view(), name='idea-feed'),
    url(r'^new-idea/$', views.NewIdeaView.as_view(), name='new-idea'),
    url(r'^myideas/$', views.MyIdeasView.as_view(), name='myideas'),
    url(r'^view-idea-page/$', views.ViewIdeaPageView.as_view(), name='view-idea-page'),
    url(r'^edit-idea-page/$', views.EditIdeaPageView.as_view(), name='edit-idea-page'),
    url(r'^editprofile/$', views.EditProfileView.as_view(), name='editprofile'),
    url(r'^share/$', views.ShareView.as_view(), name='share'),
    url(r'^welcome/$', views.WelcomeView.as_view(), name='welcome'),
    url(r'^error/$', views.ErrorView.as_view(), name='error'),
    url(r'^jet/$', views.JetView.as_view(), name='jet'),
    url(r'^jet-edit/$', views.JetEditView.as_view(), name='jet-edit')
    #url(r'^(?P<referrer>\w+)/$', views.referrer, name='referrer')
)

zaplings_django/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'zaplings_django.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'/?', include('zaplings.urls', namespace="zaplings")),
    #url(r'/', include('zaplings.urls', namespace="zaplings")),
)

zaplings/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import datetime


class IdeaType(models.Model):
    ideatype = models.CharField(max_length=50)

    def __unicode__(self):
        return self.ideatype


class Idea(models.Model):
    creator = models.ForeignKey(User)
    ideatype = models.ForeignKey(IdeaType)
    title = models.CharField(max_length=40)
    tagline = models.CharField(max_length=40)
    description = models.CharField(max_length=100)
    notes = models.CharField(max_length=10000)
    ispublic = models.BooleanField() # something for "if user has public ideas" 
    isfunding = models.BooleanField()
    haspage = models.BooleanField()
    
    def __unicode__(self):
        return self.title


class FeaturedIdea(models.Model):
    idea = models.ForeignKey(Idea)

    def __unicode__(self):
        return self.idea.title


class IdeaTeam(models.Model):
    member = models.ForeignKey(User)
    idea = models.ForeignKey(Idea)
    isadmin = models.BooleanField()

    def __unicode__(self):
        return "%s is member of idea %s" % \
                (member.username, idea.title)


class Love(models.Model):
    tagname = models.CharField(max_length=200)
    issuggested = models.BooleanField()

    def __unicode__(self):
        return self.tagname


class Offer(models.Model):
    tagname = models.CharField(max_length=200)
    issuggested = models.BooleanField()

    def __unicode__(self):
        return self.tagname


class Need(models.Model):
    tagname = models.CharField(max_length=200)
    issuggested = models.BooleanField()

    def __unicode__(self):
        return self.tagname


class UserLove(models.Model):
    user = models.ForeignKey(User)
    love = models.ForeignKey(Love)

    def __unicode__(self):
        return ' '.join([self.user.username, "loves", self.love.tagname])


class UserNeed(models.Model):
    user = models.ForeignKey(User)
    need = models.ForeignKey(Need)

    def __unicode__(self):
        return ' '.join([self.user.username, "needs", self.need.tagname])


class UserOffer(models.Model):
    user = models.ForeignKey(User)
    offer = models.ForeignKey(Offer)

    def __unicode__(self):
        return ' '.join([self.user.username, "offers", self.offer.tagname])


class NewUserEmail(models.Model):
    email = models.EmailField(max_length=60, unique=True)

    def __unicode__(self):
        return self.email


class LoveText(models.Model):
    user = models.ForeignKey(User, unique=True)
    text = models.CharField(max_length=1000)

    def __unicode__(self):
        return ' '.join(["Love text for", self.user.username])


class OfferText(models.Model):
    user = models.ForeignKey(User, unique=True)
    text = models.CharField(max_length=1000)

    def __unicode__(self):
        return ' '.join(["Offer text for", self.user.username])


class NeedText(models.Model):
    user = models.ForeignKey(User, unique=True)
    text = models.CharField(max_length=1000)

    def __unicode__(self):
        return ' '.join(["Need text for", self.user.username])


class UserRsvp(models.Model):
    """
    Keep timestamps of rsvp's
    """
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now=True, auto_now_add=True)

    def __unicode__(self):
        return "%s rsvp'd at %s" % (self.user.username, self.date)



class Where(models.Model):
    user = models.ForeignKey(User, unique=True)
    radius = models.IntegerField(blank=True)
    zipcode = models.CharField(max_length=10, blank=True)
    place = models.CharField(max_length=100, blank=True)
    hangout = models.BooleanField()

    def __unicode__(self):
        return ' '.join([self.user.username + "'s",
                         "where preferences"])


class When(models.Model):
    user = models.ForeignKey(User, unique=True)
    weekdays = models.BooleanField()
    weekends = models.BooleanField()
    mornings = models.BooleanField()
    afternoons = models.BooleanField()
    evenings = models.BooleanField()
    nights = models.BooleanField()
    utc_offset = models.IntegerField()

    def __unicode__(self):
        return ' '.join([self.user.username + "'s",
                         "when preferences"])


class FeedBack(models.Model):
    user = models.ForeignKey(User)
    feedback_type = models.CharField(max_length=30)    
    feedback_subject = models.CharField(max_length=200,   blank=True)    
    feedback_response = models.CharField(max_length=2000, blank=True)    

    def __unicode__(self):
        subject = self.feedback_subject
        return "feedback from [%s] on %s (%s)" % \
                    (self.user.username,
                     subject if subject else 'No subject provided',
                     self.feedback_type)


class Referrer(models.Model):
    referrer = models.ForeignKey(User, related_name="user_referrer")
    # email address of referred user    
    referree = models.ForeignKey(User, related_name="user_referree", unique=True) 

    def __unicode__(self):
        return "%s referred %s" % (self.referrer.username, self.referree.username)

zaplings/templates/zaplings/comments.html
<!doctype html>

{% load static %}

<html class="no-js" lang="en">
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Zaplings | Grow.</title>
		<link rel="stylesheet" href="{% static "style.css" %}" />
		<link href='http://fonts.googleapis.com/css?family=Varela+Round|Open+Sans:400,300' rel='stylesheet' type='text/css'>
		<script src="{% static "js/vendor/modernizr.js" %}"></script>
		<script src="{% static "js/vendor/jquery.js" %}"></script>
		<script src="{% static "./js/jquery.selectric.min.js" %}"></script>	

	</head>
	<body>
	  
		<div class="wrapper">
		
			{% include "./zaplings/header.html" %}

			<div class="row full-width">
				<div class="list-heading medium-6 medium-offset-2 small-9 columns">
					<h3>Discussion for {{ idea.title }}</h3>
				</div>
				<div class="list-filter medium-2 small-3 columns end">
						<select>
							<option>Newest first</option>
							<option>Earliest first</option>
							<option>Most popular</option>
							<option>Most unpopular</option>
						</select>
				</div>
			</div>

				<!-- for comment in idea.comment, display in order of net plus (plus - minus). Also only allow user to vote once (up or down) on any comment. -->

			<form id="form-comments">
				<div class="row full-width">
					<div class="medium-8 medium-offset-2 columns">
						<h6 class="no-margin-bottom">username</h6>
						<button id="comment-submit" type="submit" class="button success small round">Share</button>
						<div class="overflow-div"><textarea id="new-comment" placeholder="New question, comment, or suggestion"></textarea></div>
					</div>
				</div>
				<div class="row full-width">
					<div class="comment medium-8 medium-offset-2 columns">
						<a class="no-decoration" href="http://www.zaplings.com/{{ user.username }}"><h6 class="no-margin-bottom">username</h6></a>
						<p class="comment-content">This is a comment. It's not a very good comment. It doesn't say much but it says something. It's not relevant to this idea, except for the fact that this isn't actually an idea's comment page in the first place, so I guess it's just as relevant as this page itself.</p>
						<strong><a class="plus" href="#">+</a>&nbsp;|&nbsp;<a class="minus">&#8211;</a></strong>&nbsp;&nbsp;<span class="count">(

						<!-- replace "45" below with upvote variable and "7" with downvote variable. I need to figure out how to increment the count with jQuery-->

						<span class="upvotes">45</span>&nbsp;|&nbsp;<span class="downvotes">7</span>)</span>&nbsp;&nbsp;<a class="reply" href="#">reply</a>
					</div>
				</div>
				<div class="row full-width">
					<div class="comment medium-8 medium-offset-2 columns">
						<a class="no-decoration" href="http://www.zaplings.com/{{ user.username }}"><h6 class="no-margin-bottom">username</h6></a>
						<p class="comment-content">This is a comment. It's not a very good comment. It doesn't say much but it says something. It's not relevant to this idea, except for the fact that this isn't actually an idea's comment page in the first place, so I guess it's just as relevant as this page itself.</p>
						<strong><a class="plus" href="#">+</a>&nbsp;|&nbsp;<a class="minus">&#8211;</a></strong>&nbsp;&nbsp;<span class="count">(<span class="upvotes">45</span>&nbsp;|&nbsp;<span class="downvotes">7</span>)</span>&nbsp;&nbsp;<a class="reply" href="#">reply</a>
					</div>
				</div>
				<div class="row full-width">
					<div class="comment medium-7 medium-offset-3 small-11 small-offset-1 columns">
						<a class="no-decoration" href="http://www.zaplings.com/{{ user.username }}"><h6 class="no-margin-bottom">username</h6></a>
						<p class="comment-content">This is a comment. It's not a very good comment. It doesn't say much but it says something. It's not relevant to this idea, except for the fact that this isn't actually an idea's comment page in the first place, so I guess it's just as relevant as this page itself.</p>
						<strong><a class="plus" href="#">+</a>&nbsp;|&nbsp;<a class="minus">&#8211;</a></strong>&nbsp;&nbsp;<span class="count">(<span class="upvotes">45</span>&nbsp;|&nbsp;<span class="downvotes">7</span>)</span>&nbsp;&nbsp;<a class="reply" href="#">reply</a>
					</div>
				</div>
			</form>
			<div class="push"></div>
		</div>
		
		{% include "./zaplings/footer.html" %}
			
	    <script src="{% static "js/foundation.min.js" %}"></script>
		<script type="text/javascript">
	  		$(document).foundation();
		</script>
		<script type="text/javascript">
			$(document).ready(function(){
				$('select').selectric();

				$('#form-comments').submit(function() {
				var values = $('#form-comments').serialize();
				});

				$('.reply').click(function() {
					$('.reply-div').remove();
					$(this).parent().parent().after('<div class="reply-div row full-width"><div class="medium-7 medium-offset-3 small-offset-1 columns"><h6 class="no-margin-bottom">username</h6><button id="comment-submit" type="submit" class="button success small round">Share</button><div class="overflow-div"><textarea id="new-comment" placeholder="Reply with a question, comment, or suggestion"></textarea></div></div></div>');
					return false;
				});
			});
		</script>
	</body>
</html>

zaplings/templates/zaplings/creation-stages.html
<!doctype html>

{% load static %}

<html class="no-js" lang="en">
    <head>  
    
        {% include "./zaplings/head.html" %}
        <!--<link rel="stylesheet" href="{% static "superslides/dist/stylesheets/superslides.css" %}">-->
        <link rel="stylesheet" href="{% static "./font-awesome/css/font-awesome.min.css" %}">
        
        <link rel="stylesheet" type="text/css" href="{% static "./slick/slick.css" %}"/>
    
    </head>
    <body>
      
        <div class="wrapper">

            {% include "./zaplings/header.html" %}
            
            <div class="row no-margin-bottom">
                <div class="no-select relative-container medium-8 medium-centered columns">
                    <h2 class="centerText three-margin-top add-margin-bottom">The creation process</h2>
                    <div class="centerText single-item">
                        <div>
                            <i class="fa fa-bolt fa-4x"></i>
                            <p class="lead half-margin-top">Inspiration</p>
                            <p class="leftText">It may strike at any moment. Keep all your ideas secure in one place with your private idea book. Share it instantly or start a project page privately.</p>
                            <p class="leftText">Grow an idea from Inspiration to Validation by sharing it with your target audience to gain valuable perspective. If your fear of idea theft is so strong that it prevents you from getting started, we will help you file a provisional patent. But you must promise to get over this fear, because there are many actual risks you must face if your creation is to succeed.</p>
                        </div>
                        <div>
                            <i class="fa fa-check fa-4x"></i>
                            <p class="lead half-margin-top">Validation</p>
                            <p class="leftText">We usually like our own ideas best. However, success depends on whether others actually want or need your creation. The easiest way to find out is to ask.</p>
                            <p class="leftText">Test your idea with an audience that shares your passion. Grow from Validation to Transformation by asking and answering questions, then refine the concept based on feedback. As your idea evolves, so will you.</p>
                        </div>
                        <div>
                            <img class="fa centerImg" src="{% static './images/butterfly.png' %}" height="80px" width="80px">
                            <p class="lead half-margin-top">Transformation</p>
                            <p class="leftText">Maybe you've heard it before - ideas are cheap; execution is what matters. The lightbulb moment is only the beginning. It's so important to stay open to fresh perspectives - it makes the difference between thriving and just surviving.</p>
                            <p class="leftText">This stage is about the evolution of the concept and of yourself. Your project page keeps a history of your idea's changes, to show how it has transformed over time. To demonstrate your own progress, share updates on what you've been working on to build a portfolio one day at a time.</p>
                        </div>
                        <div>
                            <i class="fa fa-users fa-3x"></i>
                            <p class="lead half-margin-top">Team formation</p>
                            <p class="leftText">As the Zaplings community grows, we will start introducing you to people who can help realize your dream. Based on your loves, offers, and needs, we will introduce you to people who share your passion and have the expertise you seek.</p>
                            <p class="leftText no-margin-bottom">In the meantime, friends can make introductions for each other on Zaplings. No matching algorithm will ever be as valuable or trusted as personal recommendations. By inviting friends to meet up (or to join Zaplings), you earn points toward a Connector badge. We will introduce top Connectors to each other and quite possibly eliminate a degree of separation across the globe.</p>
                        </div>
                        <div>
                            <i class="fa fa-cogs fa-3x"></i>
                            <p class="lead half-margin-top">Collaboration</p>
                            <p class="leftText">To make the impact you desire, it's so important to have clear communication with your team. In time, Zaplings will provide a simple collaboration tool to help you organize your thoughts, tasks, and projects. </p>
                            <p class="leftText">To move from Collaboration to Implementation phase, you must show the community that you are ready to accept funding to launch your product, service, or art. By working through these first five stages, your project earns points. Once you reach the required score, you will have the option to crowdfund your concept.</p>
                        </div>
                        <div>
                            <i class="fa fa-paper-plane fa-3x"></i>
                            <p class="lead half-margin-top">Implementation</p>
                            <p class="leftText">Once you've grown your concept, your team, and yourself, you are ready to take your project to the next level. Many ideas require some kind of funding to reach their full potential. We can help you find it.</p>
                            <p class="leftText">Unlike some crowdfunding platforms, the Zaplings team will not be a gatekeeper who decides which ideas deserve funding and which do not. Instead, by working through the stages with the community, you will have co-created the concept with your audience, who will be all the more excited to help you reach your goal.</p>
                        </div>
                        <div>
                            <i class="fa fa-globe fa-4x"></i>
                            <p class="lead half-margin-top">Impact creation</p>
                            <p class="leftText">The launch of your project is not the finish line, but a new beginning. Now is your chance to help create the world you seek. What matters most to you and your organization? Of course, it is important to make money in order to sustain your creation. But what else? How can your activities have a powerful positive impact on the world around you?</p>
                            <p class="leftText">Zaplings will suggest ways to integrate your ideals and practices so that no sacrifice needs to be made between profit and purpose. Your integrity will not be lost on your audience, who will be all the more loyal to your mission.</p>
                        </div>
                    </div>
                    <div id="process-arrows">
                        <div class="process-prev">
                            <i class="fa fa-chevron-left"></i>
                        </div>
                        <div class="process-next">
                            <i class="fa fa-chevron-right"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="centerText medium-8 medium-centered columns">
                    <a href="{% url "zaplings:signup" %}"><button class="half-margin-right button round success">Join Zaplings</button></a><!--<a href=""><button class="button round small light">Earn badges</button></a>-->
                </div>
            </div>
            
            <div class="push"></div>
        </div>
        
        {% include "./zaplings/footer.html" %}
            
        <script src="{% static "js/foundation.min.js" %}"></script> 
        <script type="text/javascript">
            $(document).foundation();
        </script>
        
<!--        <script type="text/javascript">
        $(document).ready(function(){
            $('#slides').superslides({
                inherit_height_from: '#creation-stages-slider',
                animation_speed: 1000,
                animation: 'slide'
            });
        });
        </script>
        {% include "./zaplings/superslides-scripts.html" %}-->
        
        <script type="text/javascript" src="{% static "./slick/slick.min.js" %}"></script> 
        <script src="{% static "./js/creation-process.js" %}"></script>
        
        {% include "./zaplings/end-scripts.html" %}
    </body>
</html>

zaplings/templates/zaplings/feedback-reveal.html
{% load static %}
<script src="{% static "./js/jquery.selectric.min.js" %}"></script>
<div class="row">
	<div class="centerText medium-10 medium-offset-1 columns end">
		<form id="form-feedback" action="{% url "zaplings:record_feedback" %}" method="post"/>
                        {% csrf_token %}
			<h3>Share feedback</h3>
			<p>Questions? Issues with the site? Let us know.</p>
			<div class="medium-10 medium-offset-1 columns">
				<select name="feedback-type">
					<option value="question">Question</option>
					<option value="comment">Comment</option>
					<option value="suggestion">Suggestion</option>
					<option value="issue">Website issue</option>
					<option value="other">Other - Describe in subject field</option>
				</select>
			</div>
			<input type="text" name="feedback-subject" placeholder="Subject (optional)"/>
			<textarea rows="3" name="feedback-response" placeholder="Share your thoughts..."></textarea>
			<div class="centerText">
				<button type="submit" class="button round success">Send</button>
				<button class="close-reveal-modal button round light">Cancel</button>
			</div>
		</form>
	</div>
</div>

<script type="text/javascript">
	$(document).ready(function(){
		$('select').selectric()
	});
</script>

zaplings/templates/zaplings/loves.html
<!doctype html>

{% load static %}

<html class="no-js" lang="en">
	<head>	
	
		{% include "./zaplings/head.html" %}
    	<script type="text/javascript" src="{% static "./js/check_browser_close.js" %}"></script>
  </head>
  <body>
	  
	<div class="wrapper">

		{% include "./zaplings/header.html" %}
	  		
		<h2 class="three-margin-top no-margin-bottom centerText">What do you love?</h2>
		<form id="love-tags" action="{% url "zaplings:record_loves" %}" method="post">
		    {% csrf_token %}
	  		<div class="row">
				<div class="large-6 medium-6 small-12 medium-offset-3 columns">
					<p class="min-tags centerText accent">Please add at least 5 tags to continue.</p>
					<input class="input-tags" type="text" placeholder="I love... (press return to add)"/>
					<div class="continue-delay hidden">Keep going! More tags allow stronger connections.
						<div class="continue-tags">
							<a href="{% url "zaplings:offers" %}">
								<button id="next-offer" type="submit" class="button success round small">Next: What do you offer?</button>
							</a>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="large-8 medium-8 small-12 columns medium-offset-2">
					<div class="suggestion-box">
					{% for suggested_love in suggested_loves %} 
						<input id="love-suggest-{{ suggested_love.id }}" class="vis-hidden" type="checkbox" name="love-tag" value="{{ suggested_love.id }}">
							<label class="tag button small light round" for="love-suggest-{{ suggested_love.id }}"> {{ suggested_love.tagname }} </label>
{% endfor %}
					</div>
				</div>
			</div>	
		</form>

		<div id="signup-reveal" class="reveal-modal" data-reveal>
			{% include "./zaplings/signup-reveal.html" %}
		</div>


		<div class="push"></div>
		</div>

		{% include "./zaplings/footer.html" %}
		
    <script src="{% static "js/foundation.min.js" %}"></script>	
	<script type="text/javascript">
  		$(document).foundation();
	</script>
	<script type="text/javascript">
		$(document).ready(function() {

			var loveNum = 12;
 
			$('.suggestion-box').change(function(){
				if ($('input:checked').length > 4) {
					$('.continue-delay').removeClass('hidden');
				}
      				$('#next-offer').attr('disabled', $('input:checked').length < 5);
			});

			$('.input-tags').keypress(function (e) {
				var text = $(this).val();
					if (e.which == 13 && text != '') {
						loveNum++;
						$('.input-tags').val('');						
				  		$('.suggestion-box').prepend('<input id="love-suggest-'+loveNum+'" class="vis-hidden" type="checkbox" name="love-tag-new" value="'+text+'" checked><label class="tag button small light round" for="love-suggest-'+loveNum+'">'+text+'</label>');
						e.preventDefault();	
						$(this).focus().select();

						if ($('input:checked').length > 4) {
							$('.continue-delay').removeClass('hidden');
						}
						$('#next-offer').attr('disabled', $('input:checked').length < 5);
					}
					else if (e.which == 13 && text == ''){
						e.preventDefault();
				        return false;
					};
			});
			
			$('.suggestion-box').on('click', 'label', (function(){
				$(this).toggleClass('selected').blur();
			}));

			$('#love-tags').submit(function() {
				var values = $('#love-tags').serialize();
			});
		});
	</script>
	<script type="text/javascript">
		window.onbeforeunload = function(e) {
		    return 'Your answers will not be saved until you click the "Next" button.';
		};
	</script>
	
	 {% include "./zaplings/end-scripts.html" %}
 </body>
</html>

zaplings/templates/zaplings/profile-love.html
<!doctype html>

{% load static %}

<html class="no-js" lang="en">
    <head>  
    
        {% include "./zaplings/head.html" %}
    
  </head>
  <body>
      
    <div class="wrapper">
    
        {% include "./zaplings/header.html" %}
     
        <div class="row hide-for-small-only">
            <div class="medium-6 medium-offset-3 columns end">
                <img class="profile-image" src="{% static "./images/default-profile.png" %}" alt="Profile image" width="75px" height="75px"/>
            </div>
        </div>
        
        <!-- If username is added, display <h3>firstName lastName</h3> in place of button -->
        <div class="row hide-for-small-only">
            <div class="centerText medium-6 medium-offset-3 columns end">
                <a href="#" data-reveal-id="signup-reveal"><button class="button round">Create username</button></a>
            </div>
        </div>
        
        <div class="row show-for-small-only">
            <div class="small-12 columns">
                <img class="small-profile-image" src="{% static "./images/default-profile.png" %}" alt="Profile image" width="75px" height="75px"/>     
            </div>
        </div>  
        
        <!-- If username is added, display username in place of button -->
        <div class="row show-for-small-only">
            <div class="small-12 centerText columns">
                <a href="#" data-reveal-id="signup-reveal"><button class="button round">Create username</button></a>
            </div>  
        </div>  

        <div id="signup-reveal" class="reveal-modal" data-reveal>
            {% include "./zaplings/signup-reveal.html" %}
        </div>
        
        
        <div class="row full-width">
            <div id="profile-info" class="medium-8 small-10 small-offset-1 medium-offset-2 columns">
                <a href="{% url 'zaplings:loves' %}"><button class="intro-questions button success large round">What do you love?</button></a>
                <button class="intro-questions button round small disabled">What do you offer?</button>
                <button class="intro-questions button round small disabled">What do you need?</button>
            </div>  
        </div>  

        <div class="footer row full-width">
                <div class="social-media">
                    <a href="#"><img class="social-button" src="{% static "./images/facebook-icon.png" %}" alt="Facebook"></a>
                    <a href="#"><img class="social-button" src="{% static "./images/twitter-icon.png" %}" alt="Twitter"></a>
                    <a href="#"><img class="social-button" src="{% static "./images/linkedin-icon.png" %}" alt="LinkedIn"></a>
                </div>  
            </div>
        
    <div id="edit-name-reveal" class="reveal-modal" data-reveal>
        <form id="full-name">
            <div class="medium-8 small-12 columns end">
                <h3>Edit name</h3>
                <input id="last-name" type="text" placeholder="Last name" value="{{ lastName }}"/>
                <div id="overflow-div"><input id="first-name" type="text" placeholder="First name" value="{{ firstName }}"/></div>
                <div>
                    <button type="submit" class="button round success">Save</button>
                    <button class="button round light">Cancel</button>
                </div>  
            </div>
        </form>
    </div>  

        <div class="push"></div>
    </div>

    {% include "./zaplings/footer.html" %}
            
                
    <script src="{% static "./js/foundation.min.js" %}"></script>       
    <script type="text/javascript">
      $(document).foundation();
    </script>   
    

  </body>
            

zaplings/templates/zaplings/superslides-scripts.html
{% load static %}

<script src="{% static "js/jquery.animate-enhanced.min.js" %}"></script>
<script src="{% static "js/jquery.easing.1.3.js" %}"></script>
<script src="{% static "superslides/dist/jquery.superslides.js" %}" type="text/javascript" charset="utf-8"></script>